chore: refactor release workflow to separate release notes processing into dedicated step and update dependencies accordingly

diff --git a/.github/workflows/release-checkout.yaml b/.github/workflows/release-checkout.yaml
--- a/.github/workflows/release-checkout.yaml
+++ b/.github/workflows/release-checkout.yaml
@@ -75,7 +75,7 @@ jobs:
       prerelease: ${{ steps.read_meta.outputs.prerelease }}
       merge_option: ${{ steps.read_meta.outputs.merge_option }}
       source_branch: ${{ steps.read_meta.outputs.source_branch }}
-      release_notes: ${{ steps.read_meta.outputs.release_notes }}
+      release_notes: ${{ steps.release_notes.outputs.release_notes }}
 
     steps:
       - name: ⬇️ Checkout repository
@@ -94,27 +94,28 @@ jobs:
             exit 1
           fi
           
-          if [ ! -f .release_notes.md ]; then
-            echo "::error ::release_notes.md file not found!"
-            exit 1
-          fi
-    
           PREVIOUS_TAG=$(jq -r '.previous_tag' .release-meta.json)
           NEW_TAG=$(jq -r '.new_tag' .release-meta.json)
           PRERELEASE=$(jq -r '.prerelease' .release-meta.json)
           MERGE_OPTION=$(jq -r '.merge_option' .release-meta.json)
           SOURCE_BRANCH=$(jq -r '.source_branch' .release-meta.json)
 
-          # Read release notes from files
-          # Using base64 encoding to safely handle multiline content in GitHub Actions outputs
-          RELEASE_NOTES=$(base64 -w 0 .release_notes.md)
-
           echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
           echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
           echo "prerelease=$PRERELEASE" >> $GITHUB_OUTPUT
           echo "merge_option=$MERGE_OPTION" >> $GITHUB_OUTPUT
           echo "source_branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT
-          echo "release_notes=$CHANGELOG" >> $GITHUB_OUTPUT
+
+      - name: 🔍 Read .release_notes.md
+        id: release_notes
+        run: |
+          if [ ! -f .release_notes.md ]; then
+            echo "::error ::release_notes.md file not found!"
+            exit 1
+          fi
+          RELEASE_NOTES=$(base64 -w 0 .release_notes.md)
+
+          echo "release_notes=$RELEASE_NOTES" >> $GITHUB_OUTPUT
 
       - name: 📟 Summary
         if: always()
@@ -126,4 +127,4 @@ jobs:
           echo "::notice ::🚧 Merge option: ${{ steps.read_meta.outputs.merge_option }}"
           echo "::notice ::🚧 Source Branch: ${{ steps.read_meta.outputs.source_branch }}"
           # Decode and display
-          echo "::notice ::🚧 Release Notes Preview: $(echo "${{ steps.read_meta.outputs.release_notes }}" | base64 -d | head -n 3)"
+          echo "::notice ::🚧 Release Notes Preview: $(echo "${{ steps.release_notes.outputs.release_notes }}" | base64 -d | head -n 3)"
